language: java
jdk:
  - openjdk8
## gpg stuff
before_install:
  - if [ ! -z "$GPG_EXECUTABLE" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_EXECUTABLE" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
## default build
script: mvn --settings .travis/settings.xml -U clean verify
## release on tag
deploy:
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      tags: true
## disable emailing
#notifications:
#    email: false